openapi: 3.0.0
info:
  title: Query API
  version: 1.0.0
paths:
  /query:
    post:
      summary: Retrieve relevant content and generate response based on book content
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query_text:
                  type: string
                  description: The user's question or selected text.
                chapter_id:
                  type: string
                  format: uuid
                  nullable: true
                  description: Optional ID of the chapter for contextual queries.
      responses:
        '200':
          description: Query processed successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  response_text:
                    type: string
                    example: "The answer to your question is..."
                  source_segments:
                    type: array
                    items:
                      type: string
                    example: ["segment 1", "segment 2"]
        '400':
          description: Invalid request payload.
        '500':
          description: Internal server error.